### PR TITLE
Handle possible errors with transport.setopts and transport.getopts

### PR DESCRIPTION
**Pull request by whatyouhide**
I got bit by this in Redix or Xandra, I don't remember, but I think `with` makes this so easy to handle that it's not worth not handling it :D

### CODE REVIEW

**Comment by ericmj** [comment]
We should probably figure out how we want to do transport and inet functionality. Right now it's kind of a hack with `transport_to_inet/1`. Do we want to support any transport or is it fine with only `gen_tcp` and `gen_ssl`?

**Comment by whatyouhide** [comment]
@ericmj yeah right now there's another ack which is even more annoying to overcome IMO, that is, we do `stream() when tag in [:tcp, :ssl]`. `transport_to_inet/1` is easily solveable but the guard friendly message tag might not be that easy?

**Comment by michalmuskala** [comment]
One approach could be what `ranch` does and wrap everything in behaviour modules for transports and don't use `gen_tcp` or `ssl` directly.

**Comment by whatyouhide** [comment]
@michalmuskala we would definitely do that (that's what I meant by "transport_to_inet/1 is easily solveable") and that solves of course all the operations you do on a transport, but it doesn't solve the tagging of messages for active sockets.

**Comment by michalmuskala** [comment]
ranch solves that by requiring transports to export a `messages/0` function - it returns all the tags, so you can do something like:

```erlang
{OK, Closed, Error} = Transport:messages(),
Transport:setopts(Socket, [{active, once}]),
receive
        {OK, Socket, Data} ->
                io:format("data received: ~p~n", [Data]);
        {Closed, Socket} ->
                io:format("socket got closed!~n");
        {Error, Socket, Reason} ->
                io:format("error happened: ~p~n", [Reason])
end.
```

**Comment by whatyouhide** [comment]
@michalmuskala that's an interesting idea indeed. The problem is that we don't handle the `receive`, plus we don't know the shape of the messages of the transports, right? Or are transports forced to send those three tuples, error/closed/ok?

**Comment by michalmuskala** [comment]
I think all the standard transports (`gen_tcp`, `gen_udp` and `ssl`) all have the same shape, it's just the tag that changes.

**Comment by whatyouhide** [comment]
Yeah I personally like the idea. @ericmj if you agree I can send a PR with what it could look like in HTTP/1 before implementing for HTTP/2

**Comment by ericmj** [comment]
Yes, the main issue is that it's the users job to make sure they match on the correct message.

**Comment by whatyouhide** [comment]
@ericmj that's an issue with forcing the transport to be `:ssl | :gen_tcp` as well though. Users still have to take care of messages themselves.

**Comment by michalmuskala** [comment]
What if there was a `XHTTP.messages(conn)` callback that would return the tags for the user to match on? Not super convenient, but actually doable.

**Comment by whatyouhide** [comment]
@michalmuskala yeah I had something like that in mind, you can't expose the transport and have people use the behaviour after all. I'm 👍 for something like this I think, I would like to try how it looks in code though.

**Comment by josevalim** [comment]
> Yes, the main issue is that it's the users job to make sure they match on the correct message.

I thought the plan was to simply let the user give us the whole message and we return if we used it or not?

**Comment by whatyouhide** [comment]
@josevalim I thought so as well. However, that means that we would consume messages when they're not meant for HTTP (we lose selective receive).

**Comment by ericmj** [comment]
I don't think it's viable to have users give us all messages received. If you have 100 connections do you need to try all messages against all 100 connections? We need to document what messages they are expected to receive so they can handle them as they want.

**Comment by josevalim** [comment]
That approach is not extensible at all. Imagine we add a new protocol or a new feature or a bug fix or anything that may change in the future, now we need to tell everyone to change their messages.

> If you have 100 connections do you need to try all messages against all 100 connections?

If you have 100 connections you need to do that regardless, except that now we are coping out and saying the user should do it and leaking it all around. I know there is a bigger conceptual issue here, which is in that we can compose receives, but being to abstract over the messages was one of my initial design goals for the client.

> @josevalim I thought so as well. However, that means that we would consume messages when they're not meant for HTTP (we lose selective receive).

I am not sure I understand. The user code can still rely on selective receives and leave the catch all for last. If you are saying the user may want to use selective receiving HTTP messages, then we can document the messages for those going for lol-speed, but I would rather not push that as the default scenario. Especially because most Gen* abstraction don't rely on selective receives anyway.

**Comment by michalmuskala** [comment]
All messages include the socket reference. So if you had 100 connections, you could just fetch the right socket for that reference and continue with that instead of trying to match for a 100 connections.

**Comment by josevalim** [comment]
Agreed. And none of that excludes us from handling the messages for users - you can always drop down to something specific if you want to.

**Comment by michalmuskala** [comment]
So we would probably need two interfaces, then? The low level one when you can fetch the tag and the socket ref and do all of it yourself (you could also use it with a selective receive in that case) and the high level one when you do something like:

```elixir
def handle_info(other, state) do
  case XHTTP.handle_message(other, state.conn) do
    {:ok, data} -> 
      # message for this conn
    :error ->
      # unknown message
  end
end
```

Though I have to say, I'm not thrilled for that API either.

**Comment by whatyouhide** [comment]
@michalmuskala we can still do all this on top of the existing interfaces, both for HTTP/1 and HTTP/2 because both return `:unknown` rn (from `Conn.stream/2`) when an unknown message is passed. @josevalim your plan sounds good to me, to have `Conn.stream/2` take all messages (again it already does this) and document the specific ones for lolspeed freaksies.

**Comment by ericmj** [comment]
> I am not sure I understand. The user code can still rely on selective receives and leave the catch all for last. If you are saying the user may want to use selective receiving HTTP messages, then we can document the messages for those going for lol-speed, but I would rather not push that as the default scenario. Especially because most Gen* abstraction don't rely on selective receives anyway.

We are still going to keep the same API where the `stream` function can ignore unknown messages.

> All messages include the socket reference. So if you had 100 connections, you could just fetch the right socket for that reference and continue with that instead of trying to match for a 100 connections.

This assumes that we have documented the message structure, which is what I was proposing.

**Comment by ericmj** [comment]
And then we are back to how to handle the different tags for transports both internally and for lol-speed users.

**Pull request merged**
